# agent/nodes/finalization.py

from typing import Any, Dict

from agent.state import ClaimState
from guardrails.output_validator import output_validator
from guardrails.policy_guard import policy_guard


def finalization_node(state: ClaimState) -> Dict[str, Any]:
    claim_data = state.get(
        "claim_data",
        {},
    )

    policy_clauses = state.get(
        "retrieved_policy_clauses",
        [],
    )

    adjudication = state.get(
        "adjudication_result",
        {},
    )

    fraud_assessment = state.get(
        "fraud_assessment",
        {},
    )

    policy_result = policy_guard.validate(
        claim_data=claim_data,
        policy_clauses=policy_clauses,
        adjudication=adjudication,
    )

    if not policy_result["valid"]:
        return {
            "guardrails_status": "FAILED",
            "validation_errors": policy_result["errors"],
            "current_step": "finalization_failed",
        }

    output = {
        "claim_id": claim_data.get(
            "claim_id",
            "UNKNOWN",
        ),
        "patient_identifier_anonymized": (
            "<ANONYMIZED_PATIENT>"
        ),
        "claim_status": adjudication.get(
            "claim_status",
            "QUERY_RAISED",
        ),
        "requested_amount_inr": float(
            adjudication.get(
                "requested_amount_inr",
                0,
            )
        ),
        "approved_amount_inr": float(
            adjudication.get(
                "approved_amount_inr",
                0,
            )
        ),

        # Use deduction details generated by adjudication
        "deductions": adjudication.get(
            "deductions",
            [],
        ),

        "total_deduction_inr": float(
            adjudication.get(
                "total_deduction_inr",
                0,
            )
        ),

        "ped_waiting_period_check": {
            "ped_detected": "UNKNOWN",
            "is_claim_related": False,
            "waiting_period_status": "NOT_EVALUATED",
        },

        "fraud_risk_assessment": {
            "risk_level": fraud_assessment.get(
                "risk_level",
                "LOW",
            ),
            "anomaly_flags": fraud_assessment.get(
                "anomaly_flags",
                [],
            ),
        },

        "guardrails_validation_status": "PASSED",
    }

    validation = output_validator.validate(
        output
    )

    if not validation["valid"]:
        return {
            "final_output": {},
            "guardrails_status": "FAILED",
            "validation_errors": validation["errors"],
            "current_step": "finalization_failed",
        }

    return {
        "final_output": validation["validated_output"],
        "guardrails_status": "PASSED",
        "validation_errors": [],
        "current_step": "completed",
    }