"""
ClaimGuard AI - Enterprise Synthetic Data Generator

Generates synthetic healthcare insurance data for development/testing.

IMPORTANT:
    All data generated by this script is synthetic.
    No real patient, hospital, Aadhaar, PAN, ABHA, or medical data is used.

Generated datasets:
    data/synthetic/patients.json
    data/synthetic/claims.json
    data/synthetic/icd10_data.json
    data/synthetic/hospitals.json
    data/synthetic/claim_line_items.json

    data/tariff_master/tariffs.json

    data/policies/policy_clauses.json
    data/policies/policy_documents.json
"""

from __future__ import annotations

import json
import random
import string
from datetime import date, timedelta
from pathlib import Path
from typing import Any


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 42
random.seed(SEED)

BASE_DIR = Path(__file__).resolve().parents[1]

DATA_DIR = BASE_DIR / "data"
SYNTHETIC_DIR = DATA_DIR / "synthetic"
TARIFF_DIR = DATA_DIR / "tariff_master"
POLICY_DIR = DATA_DIR / "policies"

PATIENT_COUNT = 500
CLAIM_COUNT = 2000
HOSPITAL_COUNT = 120
TARIFF_COUNT = 600


# ============================================================
# COMMON HELPERS
# ============================================================

FIRST_NAMES = [
    "Aarav", "Aditi", "Aditya", "Akash", "Amit", "Ananya",
    "Arjun", "Arun", "Ashwin", "Bhavya", "Deepak", "Divya",
    "Gaurav", "Harish", "Isha", "Karthik", "Kavya", "Manish",
    "Meera", "Mohit", "Naveen", "Neha", "Nikhil", "Pooja",
    "Pranav", "Priya", "Rahul", "Raj", "Rakesh", "Riya",
    "Rohit", "Sanjay", "Shreya", "Sneha", "Suresh", "Swathi",
    "Tanvi", "Varun", "Vijay", "Vishal"
]

LAST_NAMES = [
    "Kumar", "Sharma", "Patel", "Singh", "Reddy", "Iyer",
    "Nair", "Rao", "Gupta", "Mehta", "Verma", "Joshi",
    "Menon", "Das", "Mishra", "Pillai", "Kapoor", "Chauhan",
    "Bhat", "Saxena", "Krishnan", "Prasad", "Agarwal"
]

CITIES = [
    "Chennai", "Bengaluru", "Hyderabad", "Mumbai", "Delhi",
    "Pune", "Kolkata", "Ahmedabad", "Coimbatore", "Jaipur",
    "Kochi", "Trivandrum", "Lucknow", "Indore", "Nagpur"
]

STATES = {
    "Chennai": "Tamil Nadu",
    "Bengaluru": "Karnataka",
    "Hyderabad": "Telangana",
    "Mumbai": "Maharashtra",
    "Delhi": "Delhi",
    "Pune": "Maharashtra",
    "Kolkata": "West Bengal",
    "Ahmedabad": "Gujarat",
    "Coimbatore": "Tamil Nadu",
    "Jaipur": "Rajasthan",
    "Kochi": "Kerala",
    "Trivandrum": "Kerala",
    "Lucknow": "Uttar Pradesh",
    "Indore": "Madhya Pradesh",
    "Nagpur": "Maharashtra",
}

POLICY_TYPES = [
    "INDIVIDUAL_HEALTH",
    "FAMILY_FLOATER",
    "SENIOR_CITIZEN",
    "CRITICAL_ILLNESS",
]

CLAIM_TYPES = [
    "CASHLESS_PRE_AUTH",
    "DISCHARGE_CLAIM",
]

CLAIM_STATUSES = [
    "APPROVED",
    "PARTIAL_APPROVAL",
    "QUERY_RAISED",
    "REJECTED",
]

PED_CONDITIONS = [
    "Type-2 Diabetes",
    "Hypertension",
    "Asthma",
    "Hypothyroidism",
    "Hyperlipidemia",
    "Coronary Artery Disease",
    "Chronic Kidney Disease",
    "None",
]

DIAGNOSES = [
    {
        "name": "Acute Cholecystitis",
        "icd10": "K81.0",
        "procedures": [
            "Laparoscopic Cholecystectomy",
            "Open Cholecystectomy",
        ],
    },
    {
        "name": "Acute Appendicitis",
        "icd10": "K35.80",
        "procedures": [
            "Laparoscopic Appendectomy",
            "Open Appendectomy",
        ],
    },
    {
        "name": "Community Acquired Pneumonia",
        "icd10": "J18.9",
        "procedures": [
            "Medical Management",
            "IV Antibiotic Therapy",
        ],
    },
    {
        "name": "Unstable Angina",
        "icd10": "I20.0",
        "procedures": [
            "Coronary Angiography",
            "Medical Management",
        ],
    },
    {
        "name": "Acute Myocardial Infarction",
        "icd10": "I21.9",
        "procedures": [
            "Coronary Angioplasty",
            "Cardiac Catheterization",
        ],
    },
    {
        "name": "Renal Calculus",
        "icd10": "N20.0",
        "procedures": [
            "Ureteroscopy",
            "Lithotripsy",
        ],
    },
    {
        "name": "Inguinal Hernia",
        "icd10": "K40.90",
        "procedures": [
            "Laparoscopic Hernia Repair",
            "Open Hernia Repair",
        ],
    },
    {
        "name": "Osteoarthritis of Knee",
        "icd10": "M17.9",
        "procedures": [
            "Total Knee Replacement",
            "Knee Arthroscopy",
        ],
    },
    {
        "name": "Cataract",
        "icd10": "H25.9",
        "procedures": [
            "Phacoemulsification",
        ],
    },
    {
        "name": "Urinary Tract Infection",
        "icd10": "N39.0",
        "procedures": [
            "Medical Management",
            "IV Antibiotic Therapy",
        ],
    },
]


ROOM_CATEGORIES = [
    ("GENERAL", 2000),
    ("SEMI_PRIVATE", 3500),
    ("PRIVATE", 5000),
    ("DELUXE", 8000),
    ("SUITE", 12000),
]


NON_PAYABLE_ITEMS = [
    "Surgical Gloves",
    "PPE Kit",
    "Sanitizer",
    "Food Charges",
    "Registration Charges",
    "Documentation Charges",
    "Administrative Charges",
    "Baby Food",
    "Attendant Charges",
    "Personal Toiletries",
    "Telephone Charges",
    "Television Charges",
]


# ============================================================
# DIRECTORY SETUP
# ============================================================

def create_directories() -> None:
    """Create all required data directories."""

    for directory in [
        SYNTHETIC_DIR,
        TARIFF_DIR,
        POLICY_DIR,
    ]:
        directory.mkdir(parents=True, exist_ok=True)


# ============================================================
# FILE WRITER
# ============================================================

def write_json(path: Path, data: Any) -> None:
    """Write JSON with readable formatting."""

    with path.open("w", encoding="utf-8") as file:
        json.dump(
            data,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ============================================================
# ID GENERATORS
# ============================================================

def random_digits(length: int) -> str:
    return "".join(random.choices(string.digits, k=length))


def generate_aadhaar() -> str:
    return random_digits(12)


def generate_pan() -> str:
    letters = "".join(random.choices(string.ascii_uppercase, k=5))
    numbers = random_digits(4)
    final_letter = random.choice(string.ascii_uppercase)
    return f"{letters}{numbers}{final_letter}"


def generate_abha() -> str:
    return f"{random_digits(8)}-{random_digits(4)}-{random_digits(4)}"


def generate_phone() -> str:
    return "9" + random_digits(9)


# ============================================================
# HOSPITAL DATA
# ============================================================

def generate_hospitals() -> list[dict[str, Any]]:
    hospitals = []

    hospital_types = [
        "MULTI_SPECIALTY",
        "TERTIARY_CARE",
        "SUPER_SPECIALTY",
        "GENERAL_HOSPITAL",
        "DAY_CARE_CENTER",
    ]

    for index in range(1, HOSPITAL_COUNT + 1):
        city = random.choice(CITIES)

        hospitals.append(
            {
                "hospital_id": f"HSP-{index:05d}",
                "hospital_name": (
                    f"{city} "
                    f"{random.choice(['City', 'Care', 'Apollo', 'Global', 'Prime', 'Metro'])} "
                    f"Hospital {index}"
                ),
                "hospital_type": random.choice(hospital_types),
                "city": city,
                "state": STATES[city],
                "pincode": random_digits(6),
                "network_status": random.choice(
                    ["NETWORK", "NON_NETWORK"]
                ),
                "registration_number": f"REG-{random_digits(10)}",
                "ipd_supported": True,
                "cashless_enabled": True,
            }
        )

    return hospitals


# ============================================================
# PATIENT DATA
# ============================================================

def generate_patients() -> list[dict[str, Any]]:
    patients = []

    for index in range(1, PATIENT_COUNT + 1):

        first_name = random.choice(FIRST_NAMES)
        last_name = random.choice(LAST_NAMES)

        city = random.choice(CITIES)

        age = random.randint(18, 82)

        gender = random.choice(
            ["MALE", "FEMALE"]
        )

        ped = random.choice(PED_CONDITIONS)

        if ped == "None":
            ped_list = []
        else:
            ped_list = [ped]

        policy_type = random.choice(POLICY_TYPES)

        sum_insured = random.choice(
            [
                300000,
                500000,
                750000,
                1000000,
                1500000,
                2000000,
                2500000,
                5000000,
            ]
        )

        policy_start = date(2024, 1, 1) + timedelta(
            days=random.randint(0, 850)
        )

        patients.append(
            {
                "patient_id": f"PAT-{index:06d}",
                "name": f"{first_name} {last_name}",
                "gender": gender,
                "age": age,
                "city": city,
                "state": STATES[city],
                "phone": generate_phone(),
                "address": (
                    f"{random.randint(1, 999)}, "
                    f"{random.choice(['Main Road', 'MG Road', 'Park Street', 'Lake View Road'])}, "
                    f"{city}"
                ),
                "aadhaar": generate_aadhaar(),
                "pan": generate_pan(),
                "abha_id": generate_abha(),
                "policy_id": f"POL-{index:06d}",
                "policy_type": policy_type,
                "sum_insured_inr": sum_insured,
                "policy_start_date": policy_start.isoformat(),
                "policy_end_date": (
                    policy_start + timedelta(days=365)
                ).isoformat(),
                "room_rent_limit_percent": random.choice(
                    [1.0, 1.5, 2.0]
                ),
                "ped_waiting_period_months": random.choice(
                    [24, 36, 48]
                ),
                "declared_peds": ped_list,
                "cumulative_claimed_inr": random.randint(
                    0,
                    int(sum_insured * 0.35)
                ),
            }
        )

    return patients


# ============================================================
# ICD-10 DATA
# ============================================================

def generate_icd10_data() -> list[dict[str, Any]]:
    codes = []

    for index, diagnosis in enumerate(DIAGNOSES, start=1):
        codes.append(
            {
                "code_id": f"ICD-{index:05d}",
                "icd10_code": diagnosis["icd10"],
                "diagnosis_name": diagnosis["name"],
                "category": (
                    diagnosis["icd10"][0]
                ),
                "description": (
                    f"Standardized ICD-10 classification "
                    f"for {diagnosis['name']}."
                ),
                "active": True,
                "version": "ICD-10",
            }
        )

    return codes


# ============================================================
# TARIFF MASTER
# ============================================================

def generate_tariffs(hospitals: list[dict[str, Any]]) -> list[dict[str, Any]]:
    tariffs = []

    procedures = [
        ("Laparoscopic Cholecystectomy", 45000, 85000),
        ("Open Cholecystectomy", 35000, 65000),
        ("Laparoscopic Appendectomy", 30000, 60000),
        ("Open Appendectomy", 25000, 50000),
        ("Coronary Angiography", 18000, 35000),
        ("Coronary Angioplasty", 120000, 250000),
        ("Cardiac Catheterization", 50000, 100000),
        ("Ureteroscopy", 40000, 90000),
        ("Lithotripsy", 35000, 80000),
        ("Laparoscopic Hernia Repair", 45000, 90000),
        ("Open Hernia Repair", 30000, 65000),
        ("Total Knee Replacement", 150000, 300000),
        ("Knee Arthroscopy", 60000, 120000),
        ("Phacoemulsification", 25000, 55000),
        ("Medical Management", 15000, 50000),
        ("IV Antibiotic Therapy", 10000, 35000),
    ]

    tariff_id = 1

    for hospital in hospitals:

        selected_procedures = random.sample(
            procedures,
            k=random.randint(6, min(12, len(procedures))),
        )

        for procedure, minimum, maximum in selected_procedures:

            base = random.randint(minimum, maximum)

            tariffs.append(
                {
                    "tariff_id": f"TAR-{tariff_id:06d}",
                    "hospital_id": hospital["hospital_id"],
                    "service_code": (
                        "PROC-" + random_digits(6)
                    ),
                    "service_name": procedure,
                    "category": "PROCEDURE",
                    "standard_tariff_inr": base,
                    "min_tariff_inr": int(base * 0.85),
                    "max_tariff_inr": int(base * 1.15),
                    "effective_from": "2026-01-01",
                    "effective_to": "2026-12-31",
                    "currency": "INR",
                }
            )

            tariff_id += 1

    # Room tariffs
    for hospital in hospitals:

        for category, price in ROOM_CATEGORIES:

            tariffs.append(
                {
                    "tariff_id": f"TAR-{tariff_id:06d}",
                    "hospital_id": hospital["hospital_id"],
                    "service_code": f"ROOM-{category}",
                    "service_name": f"{category} Room",
                    "category": "ROOM",
                    "standard_tariff_inr": price,
                    "min_tariff_inr": int(price * 0.9),
                    "max_tariff_inr": int(price * 1.2),
                    "effective_from": "2026-01-01",
                    "effective_to": "2026-12-31",
                    "currency": "INR",
                }
            )

            tariff_id += 1

    return tariffs


# ============================================================
# CLAIM DATA
# ============================================================

def random_date_between(
    start: date,
    end: date,
) -> date:

    delta = (end - start).days

    return start + timedelta(
        days=random.randint(0, max(delta, 1))
    )


def generate_claims(
    patients: list[dict[str, Any]],
    hospitals: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    claims = []

    for index in range(1, CLAIM_COUNT + 1):

        patient = random.choice(patients)
        hospital = random.choice(hospitals)
        diagnosis = random.choice(DIAGNOSES)

        procedure = random.choice(
            diagnosis["procedures"]
        )

        claim_type = random.choice(
            CLAIM_TYPES
        )

        admission_date = date(2026, 1, 1) + timedelta(
            days=random.randint(0, 220)
        )

        length_of_stay = random.randint(
            1,
            10
        )

        discharge_date = (
            admission_date
            + timedelta(days=length_of_stay)
        )

        room_limit = (
            patient["sum_insured_inr"]
            * patient["room_rent_limit_percent"]
            / 100
        )

        room_multiplier = random.choices(
            [0.8, 1.0, 1.25, 1.6, 2.0],
            weights=[20, 35, 25, 15, 5],
        )[0]

        room_charge = int(
            room_limit * room_multiplier
        )

        procedure_cost = random.randint(
            30000,
            180000
        )

        diagnostics = random.randint(
            5000,
            30000
        )

        pharmacy = random.randint(
            5000,
            40000
        )

        consumables = random.randint(
            2000,
            18000
        )

        miscellaneous = random.randint(
            1000,
            10000
        )

        room_total = room_charge * length_of_stay

        requested_amount = (
            room_total
            + procedure_cost
            + diagnostics
            + pharmacy
            + consumables
            + miscellaneous
        )

        anomaly_type = random.choices(
            [
                "NONE",
                "ROOM_RENT_EXCESS",
                "NON_PAYABLE_ITEMS",
                "TIMELINE_MISMATCH",
                "UNBUNDLING",
                "DUPLICATE_CHARGE",
                "HIGH_VALUE_ANOMALY",
            ],
            weights=[
                50,
                15,
                10,
                8,
                7,
                5,
                5,
            ],
        )[0]

        fraud_flags = []

        if anomaly_type == "ROOM_RENT_EXCESS":
            fraud_flags.append(
                "ROOM_RENT_LIMIT_EXCEEDED"
            )

        elif anomaly_type == "NON_PAYABLE_ITEMS":
            fraud_flags.append(
                "NON_PAYABLE_ITEMS_DETECTED"
            )

        elif anomaly_type == "TIMELINE_MISMATCH":
            fraud_flags.append(
                "TIMELINE_MISMATCH"
            )

        elif anomaly_type == "UNBUNDLING":
            fraud_flags.append(
                "POSSIBLE_UNBUNDLING"
            )

        elif anomaly_type == "DUPLICATE_CHARGE":
            fraud_flags.append(
                "POSSIBLE_DUPLICATE_CHARGE"
            )

        elif anomaly_type == "HIGH_VALUE_ANOMALY":
            fraud_flags.append(
                "HIGH_VALUE_ANOMALY"
            )

        if fraud_flags:
            fraud_risk = random.choice(
                ["MEDIUM", "HIGH"]
            )
        else:
            fraud_risk = random.choices(
                ["LOW", "MEDIUM"],
                weights=[90, 10],
            )[0]

        claims.append(
            {
                "claim_id": f"CLM-2026-IN-{index:06d}",
                "patient_id": patient["patient_id"],
                "policy_id": patient["policy_id"],
                "hospital_id": hospital["hospital_id"],
                "claim_type": claim_type,
                "submission_channel": random.choice(
                    ["PORTAL", "API", "TPA_PORTAL", "CLI_SIMULATION"]
                ),
                "diagnosis": diagnosis["name"],
                "icd10_code": diagnosis["icd10"],
                "procedure": procedure,
                "admission_date": admission_date.isoformat(),
                "discharge_date": discharge_date.isoformat(),
                "length_of_stay_days": length_of_stay,
                "room_category": random.choice(
                    [room[0] for room in ROOM_CATEGORIES]
                ),
                "room_charge_per_day_inr": room_charge,
                "room_eligible_per_day_inr": round(
                    room_limit,
                    2
                ),
                "procedure_cost_inr": procedure_cost,
                "diagnostics_inr": diagnostics,
                "pharmacy_inr": pharmacy,
                "consumables_inr": consumables,
                "miscellaneous_inr": miscellaneous,
                "requested_amount_inr": requested_amount,
                "policy_sum_insured_inr": patient[
                    "sum_insured_inr"
                ],
                "policy_balance_before_claim_inr": max(
                    patient["sum_insured_inr"]
                    - patient["cumulative_claimed_inr"],
                    0,
                ),
                "ped_waiting_period_months": patient[
                    "ped_waiting_period_months"
                ],
                "declared_peds": patient[
                    "declared_peds"
                ],
                "anomaly_type": anomaly_type,
                "fraud_flags": fraud_flags,
                "fraud_risk_expected": fraud_risk,
                "expected_claim_status": random.choice(
                    CLAIM_STATUSES
                ),
            }
        )

    return claims


# ============================================================
# CLAIM LINE ITEMS
# ============================================================

def generate_claim_line_items(
    claims: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    items = []

    item_id = 1

    for claim in claims:

        line_definitions = [
            (
                "ROOM_RENT",
                claim["room_charge_per_day_inr"]
                * claim["length_of_stay_days"],
            ),
            (
                "PROCEDURE",
                claim["procedure_cost_inr"],
            ),
            (
                "DIAGNOSTICS",
                claim["diagnostics_inr"],
            ),
            (
                "PHARMACY",
                claim["pharmacy_inr"],
            ),
            (
                "CONSUMABLES",
                claim["consumables_inr"],
            ),
            (
                "MISCELLANEOUS",
                claim["miscellaneous_inr"],
            ),
        ]

        for category, amount in line_definitions:

            payable = True
            deduction_reason = None

            if (
                category == "CONSUMABLES"
                and random.random() < 0.65
            ):
                payable = False
                deduction_reason = random.choice(
                    NON_PAYABLE_ITEMS
                )

            items.append(
                {
                    "line_item_id": f"LINE-{item_id:08d}",
                    "claim_id": claim["claim_id"],
                    "category": category,
                    "description": (
                        deduction_reason
                        if deduction_reason
                        else category.replace("_", " ").title()
                    ),
                    "amount_inr": amount,
                    "payable": payable,
                    "deduction_reason": deduction_reason,
                }
            )

            item_id += 1

    return items


# ============================================================
# POLICY CLAUSES
# ============================================================

def generate_policy_clauses() -> list[dict[str, Any]]:

    clauses = [
        {
            "clause_id": "POL-ROOM-001",
            "policy_type": "INDIVIDUAL_HEALTH",
            "category": "ROOM_RENT",
            "title": "Room Rent Limitation",
            "text": (
                "Eligible room rent shall be limited to the percentage "
                "of Sum Insured specified in the policy schedule. "
                "Where the insured occupies a room above the eligible "
                "limit, applicable proportional deductions may apply "
                "to associated medical expenses as specified by the policy."
            ),
        },
        {
            "clause_id": "POL-NP-001",
            "policy_type": "INDIVIDUAL_HEALTH",
            "category": "NON_PAYABLE",
            "title": "Non-Payable Items",
            "text": (
                "Expenses relating to specified non-medical and "
                "administrative consumables shall not be payable where "
                "excluded under the applicable policy terms."
            ),
        },
        {
            "clause_id": "POL-PED-001",
            "policy_type": "INDIVIDUAL_HEALTH",
            "category": "PED",
            "title": "Pre-Existing Disease Waiting Period",
            "text": (
                "Expenses related to declared pre-existing diseases "
                "may be subject to the waiting period specified in "
                "the applicable policy schedule."
            ),
        },
        {
            "clause_id": "POL-SI-001",
            "policy_type": "INDIVIDUAL_HEALTH",
            "category": "SUM_INSURED",
            "title": "Maximum Liability",
            "text": (
                "The insurer's liability shall not exceed the available "
                "Sum Insured and applicable policy limits."
            ),
        },
        {
            "clause_id": "POL-CL-001",
            "policy_type": "INDIVIDUAL_HEALTH",
            "category": "CLAIM",
            "title": "Cashless Pre-Authorization",
            "text": (
                "Cashless treatment is subject to pre-authorization, "
                "policy coverage, medical necessity, and verification "
                "of applicable exclusions and limits."
            ),
        },
        {
            "clause_id": "POL-DIS-001",
            "policy_type": "INDIVIDUAL_HEALTH",
            "category": "DISCHARGE",
            "title": "Discharge Claim Assessment",
            "text": (
                "Final discharge assessment shall consider actual "
                "treatment rendered, eligible expenses, applicable "
                "deductions, policy limits, and supporting documents."
            ),
        },
        {
            "clause_id": "POL-FRAUD-001",
            "policy_type": "INDIVIDUAL_HEALTH",
            "category": "FRAUD",
            "title": "Misrepresentation and Fraud",
            "text": (
                "Material inconsistencies, duplicate billing, artificial "
                "unbundling, fabricated documentation, or other suspicious "
                "patterns may result in investigation or query."
            ),
        },
        {
            "clause_id": "POL-CRITICAL-001",
            "policy_type": "CRITICAL_ILLNESS",
            "category": "COVERAGE",
            "title": "Critical Illness Coverage",
            "text": (
                "Critical illness benefits are payable subject to the "
                "defined covered conditions, diagnosis requirements, "
                "waiting periods, and policy limits."
            ),
        },
        {
            "clause_id": "POL-SENIOR-001",
            "policy_type": "SENIOR_CITIZEN",
            "category": "SENIOR",
            "title": "Senior Citizen Coverage",
            "text": (
                "Senior citizen claims shall be evaluated against "
                "the applicable policy schedule, co-payment provisions, "
                "waiting periods, exclusions, and admissibility rules."
            ),
        },
        {
            "clause_id": "POL-FLOATER-001",
            "policy_type": "FAMILY_FLOATER",
            "category": "FLOATER",
            "title": "Family Floater Sum Insured",
            "text": (
                "The available Sum Insured is shared among covered "
                "members of the family floater policy and shall be "
                "reduced by eligible claims during the policy year."
            ),
        },
    ]

    return clauses


# ============================================================
# POLICY DOCUMENTS
# ============================================================

def generate_policy_documents(
    clauses: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    documents = []

    grouped: dict[str, list[dict[str, Any]]] = {}

    for clause in clauses:
        grouped.setdefault(
            clause["policy_type"],
            [],
        ).append(clause)

    for policy_type, policy_clauses in grouped.items():

        documents.append(
            {
                "document_id": (
                    f"DOC-{policy_type}-2026"
                ),
                "document_type": "POLICY_GUIDELINE",
                "policy_type": policy_type,
                "effective_date": "2026-01-01",
                "version": "2026.1",
                "source": "ClaimGuard Synthetic Policy Repository",
                "clauses": policy_clauses,
            }
        )

    return documents


# ============================================================
# DATA SUMMARY
# ============================================================

def generate_summary(
    patients: list,
    claims: list,
    claim_items: list,
    hospitals: list,
    tariffs: list,
    icd10: list,
    clauses: list,
) -> dict[str, Any]:

    return {
        "generator": "ClaimGuard AI Synthetic Data Generator",
        "version": "1.0",
        "random_seed": SEED,
        "synthetic_only": True,
        "records": {
            "patients": len(patients),
            "claims": len(claims),
            "claim_line_items": len(claim_items),
            "hospitals": len(hospitals),
            "tariffs": len(tariffs),
            "icd10_data": len(icd10),
            "policy_clauses": len(clauses),
        },
    }


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    print("=" * 60)
    print("ClaimGuard AI - Enterprise Synthetic Data Generator")
    print("=" * 60)

    create_directories()

    print("\n[1/8] Generating hospitals...")
    hospitals = generate_hospitals()

    print("[2/8] Generating patients...")
    patients = generate_patients()

    print("[3/8] Generating ICD-10 dataset...")
    icd10_data = generate_icd10_data()

    print("[4/8] Generating tariff master...")
    tariffs = generate_tariffs(hospitals)

    print("[5/8] Generating claims...")
    claims = generate_claims(
        patients,
        hospitals,
    )

    print("[6/8] Generating claim line items...")
    claim_line_items = generate_claim_line_items(
        claims
    )

    print("[7/8] Generating policy knowledge...")
    policy_clauses = generate_policy_clauses()

    policy_documents = generate_policy_documents(
        policy_clauses
    )

    print("[8/8] Writing datasets...")

    write_json(
        SYNTHETIC_DIR / "patients.json",
        patients,
    )

    write_json(
        DATA_DIR / "claims" / "claims.json",
        claims,
    )

    write_json(
        SYNTHETIC_DIR / "claim_line_items.json",
        claim_line_items,
    )

    write_json(
        SYNTHETIC_DIR / "hospitals.json",
        hospitals,
    )

    write_json(
        SYNTHETIC_DIR / "icd10_data.json",
        icd10_data,
    )

    write_json(
        TARIFF_DIR / "tariffs.json",
        tariffs,
    )

    write_json(
        POLICY_DIR / "policy_clauses.json",
        policy_clauses,
    )

    write_json(
        POLICY_DIR / "policy_documents.json",
        policy_documents,
    )

    summary = generate_summary(
        patients,
        claims,
        claim_line_items,
        hospitals,
        tariffs,
        icd10_data,
        policy_clauses,
    )

    write_json(
        SYNTHETIC_DIR / "dataset_summary.json",
        summary,
    )

    print("\n" + "=" * 60)
    print("DATA GENERATION COMPLETE")
    print("=" * 60)

    for name, count in summary["records"].items():
        print(f"{name:25} : {count:,}")

    print("\nGenerated under:")
    print(f"  {SYNTHETIC_DIR}")
    print(f"  {TARIFF_DIR}")
    print(f"  {POLICY_DIR}")

    print("\nAll generated data is SYNTHETIC.")


if __name__ == "__main__":
    main()